[package]
name = "client"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# -- App (HTML)
app = { path = "../app" }
# -- Leptos
leptos = { version = "0.6.12" }
# -- WASM
console_error_panic_hook = "0.1.7"
wasm-bindgen = "0.2.92"

[lints]
workspace = true
